---

#icinga_default_host_attrs:
#  check_command: "hostalive"
#  groups:
#    - "prefix"
#  vars:
#    os: "Linux"
#    managed: "ansible"
#
#icinga_default_services:
#  - name: "def_a"
#    attrs:
#      check_command: "..."
#    notifications: "defaults"
#
#  - name: "def_b"
#    attrs:
#      check_command: "..."
#      #...
#
#icinga_default_service_notifs:
#  - name: "notif-def_ser-email"
#    attrs:
#      users: []
#      user_groups: []
#      command: "..."
#
#  - name: "notif-def_ser-sms"
#    attrs:  {}
#
#icinga_default_host_notifs:
#  - name: "notif-def_host-email"
#    state: present
#    attrs:
#      command: "mail-host-notification"
#      users:  [ "USER" ]
#      interval: "600"
#
#  - name: "notif-def_host-sms"
#     state: present
#    attrs:
#      command: "sms-host-notification"
#      users:  [ "USER" ]
#      interval: "600"
#      states: [ "Up", "Down" ]
#      types: [ "Problem", "Acknowledgement", "Recovery", "Custom", "FlappingStart", "FlappingEnd", "DowntimeStart", "DowntimeEnd", "DowntimeRemoved" ]
#      period: "workday"
#      vars:
#        sms: "enabled"
#
# Attributes "interval", "types", "states", "period", "vars" are optional.
#
#icinga_hosts:
## Host using default attributes and defining own services and notifications
## with default notifications for service check_B.
#  - name: "machine.fqdn"
#    state: "present"
#    attrs:
#      address: "IP.ADD.RE.SS"
#      address6: "fd00:dead:beef::111"
#    notifications:
#      - name: "host1_notif_1"
#        state: present
#        attrs:
#          {}
#    services:
#      - name: "check_A"
#        state: "present"
#        attrs:
#          check_command: "..."
#        notifications:
#          - name: "notif_A"
#            state: "present"
#            attrs: {}
#      - name: "check_B"
#        state: "present"
#        attrs:
#          check_command: "..."
#        notifications: "defaults"
#
## Host using default services and notifcations while defining
## attributes for check_command and groups.
#  - name: "machine.fqdn"
#    state: "present"
#    attrs:
#      address: "IP.ADD.RE.SS"
#      address6: "fd00:dead:beef::111"
#      check_command: "ping"
#      groups:
#        - "prefix"
#        - ...
#    services: "defaults"
#    notifications: "defaults"
#
## Host with default services and defining additional services with
## attributes for check_command and groups for host also defined.
#  - name: "machine.fqdn"
#    state: "present"
#    attrs:
#      address: "IP.ADD.RE.SS"
#      address6: "fd00:dead:beef::111"
#      check_command: "ping"
#      groups:
#        - "prefix"
#        - ...
#    services_combined:
#      - name: check_http
#        state: present
#        attrs:
#          check_command: http
#          vars:
#    notifications: "defaults"
#
## Host without services of notifications
#  - name: "machine.fqdn"
#    state: "present"
#    attrs:
#      address: "IP.ADD.RE.SS"
#      address6: "fd00:dead:beef::111"
#    services:
#    notifications:
#
## Host deletion. When cascade is set to 1 all dependencies (services, notifications, ...) are deleted too.
#    - name: "machine.fqdn"
#      state: "absent"
#      cascade: "1"
#      attrs:
#        address: "IP.ADD.RE.SS"
#      address6: "fd00:dead:beef::111"

#icinga_default_host_attrs:
#icinga_default_services:
#icinga_default_service_notifs:
#icinga_default_host_notifs:
#icinga_hosts:


...
